name: License audit

on:
  push:
  pull_request:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: pip install pip-licenses
      - run: npm install -g license-checker
      - run: bash scripts/audit_licenses.sh
      - run: git diff --exit-code THIRD_PARTY_LICENSES.md
